### ISSUE TITLE
Cannot save experiment data

### ISSUE THREAD

**Issue by adenton2** [sigvoiced/Pewter#2]
Hello,

I have already communicated with you via email, and you suggested that I raise the issue on Github as well. I am having trouble saving my experiments.  I get an error saying, "Error: Some error occured while uploading data. Please try again later."

If you have any ideas please let me know.

Alex

**Comment by dashayushman** [comment]
Hi @adenton2 

Refer to [This](https://github.com/sigvoiced/pewter/issues/1). I think this should solve the issue.

**Comment by adenton2** [comment]
Thanks for showing me this. Unfortunately I already came across this 
post yesterday and I checked, and I do have an "experimentdata" folder. 
Originally when I unzipped the folder it was titled, "pewter-master" so 
I tried to rename as you have to just "Pewter" but that didn't seem to 
help.

Any other suggestions?

Thanks,

Alex

**Comment by sigvoiced** [comment]
@adenton2 : Could you check the browser console and give me some more details. It seems to me that the requests are getting timed out. But I am not sure. It will be helpful if you could share the screenshots as well.

**Comment by adenton2** [comment]
Absolutely. 
[Pewter.pdf](https://github.com/sigvoiced/pewter/files/788210/Pewter.pdf)

**Comment by sigvoiced** [comment]
@adenton2 : Thanks for pointing to the right direction. I have found the issue. Right now I am a bit busy with another project of mine. I will fix the bug and push the changes very soon.

**Comment by AlbertoGhiotto** [comment]
Hi @sigvoiced,
I'm having the same problem with saving data. I saved the "Pewter" folder in the C:\Pewter root and despite having the "experimentdata" folder in the right place I'm still having this error "Error: Some error occured while uploading data. Please try again later.".

Any suggestion?

Thanks,

Alberto

**Comment by lutri-kl** [comment]
Hi Hi @sigvoiced,
I'm having the same problems as decribed above. Is there already a solution for it? I would love to use that tool.

**Comment by AlbertoGhiotto** [comment]
> Hi Hi @sigvoiced,
> I'm having the same problems as decribed above. Is there already a solution for it? I would love to use that tool.

Hi @lutri-kl, 
I don't think you will get a reply. The thing is the myo has gone out of production and a lot of projects regarding it aren't maintaned anymore.
Take a look at [this repo](https://github.com/exelban/myo-armband-nn), last year we used that code instead of pewter.

**Comment by ozgegunaydin** [comment]
Hi @sigvoiced ,
This is probably a late response but I had the same issue, and fixed it.
You are getting this error because your file exceed maximum file size that defined in "app.js"
I changed the line 29 in app.js to app.use(bodyParser.raw({limit: '500kb'}));
and it works now.
