### ISSUE TITLE
hope record time

### ISSUE THREAD

**Issue by bkhotey4** [sigvoiced/Pewter#4]
record time is about 2 seconds
Can it record long time until user push pause?
please.

**Comment by dashayushman** [comment]
@bkhotey4 This can be increased by increasing the payload upper limit for HTTP POST requests.

**Comment by BiserkaP** [comment]
@dashayushman  can you be more precise how it should be done? Is it possible to record 12-13 minutes of  arm movements?

**Comment by danrlady** [comment]
Hi @dashayushman! I just found out how to solve that (if this info is still useful for you): on the app.js file, go to the section where you can found

**app.use(bodyParser.urlencoded({ extended: false }));**

And insert a new propety on bodyParser.urlencoded, to limit of the HTTP POST request to match the limit in the bodyParser.json. It will be something like this:

**app.use(bodyParser.urlencoded({ extended: false, limit: '100mb' }));**
